name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release ex.: "10.22.0" (leave blank for latest)'
        required: false
  schedule:
    - cron: "0 0 */15 * *" # Every 15 days

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authorize
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Release
        run: cd .scripts && sh ./package.sh ${{ github.event.inputs.version }}
